# Dise침o WEB

Lo que quiero es una pagina que tenga una cabecera siempre fija, un pie siempre fijo y
que la barra se mantenga dentro

Para ello la pagina tiene 3 divs:

* yataHeader
* yataContent
* yataFooter

## Barra de navegacion

Le ponemos el logo por que queda bien 
`r colorize("red", "Podriamos usarlo para cambiar de base de datos")`

Esta barra de navegacion debe tener un icono a la izquierda para abrir un menu lateral y otro icono a la derecha para abrir otro menu en el otro lado. 
Cada uno de estos botones deberian indicar si estan abiertos o cerrados; es decir, cambiar el icono segun estado, y ademas hay que tener en cuenta que no todas las paginas necesitan esos menus, por lo que hay que ocultarlos o no si procede.

El metodo para ocultarlo sin reajustar el menu es con el atributo: **visibility: hidden**

## menus laterales

EStos no deben desplazar toda la pantalla, si no solo la parte donde aplican, 

## Implementacion

El control lo hacemos por javascript directamente y tiene lo siguientes requerimientos:

- La pesta침a tiene uno,dos o ningun submenu
- La pesta침a activa, considerando que puede haber una profundidad de menu indeterminada
- El estado actual de cada panel
- Identificar cuando se ha pulsado el boton
- Mostrar/ocultar el menu asociado
- Mostrar/ocultar el icono
- Cambiar el icono


### Objetos Panel

Necesitamos crear un objeto que contenga la informacion del panel y su estado. 
Como a priori no sabemos cuantos paneles existir치n, estos objetos se crearan en el shiny cuando se instancien y se mandaran a la aplicacion.

function Panel(name) {
  this.name = name;
  this.id   = null;  // Este seria el id
  this.leftSide = false;
  this.rightSide = false;
}

Por otro lado, en el objeto YATA deberemos mantener una tabla/mapa para almacenarlos

YATA.vars.panels

y sus funciones asociadas: get y put

Para crear el objeto usaremos la comunicacion entre R y JS:

Esto en el head

 Shiny.addCustomMessageHandler('setPanel', function(data) { $.YATA.yataSetPanel(data); }

Esto en el server

session$sendCustomMessage("setPanel", datos)

Se supone que sabemos las caracteristicas del panel, asi que enviaremos el mensaje la primera vez que se cargue el panel.

`r colorize("red", "Por ahora, la manera mejor parece hacerlo en la clase del panel")`
aunque puede haber paneles sin objeto de control, en ese caso no se podria saber, pero por otro lado
si cada click de menu envia un mensaje, si el panel no esta registrado, podemos quitar los iconos por defecto


** ES CLAVE QUE EL ID DEL TAB SEA EL ID DEL OBJETO **

Podemos dejar la definicion del panel en la propia clase R6 por ahora


yataApp

** yataTraceMenu **
** yataSetPanel **
