---
title: "Yet Another Trading Algorithm"
author: "Grandez"
date: "`r Sys.Date()`"
subtitle: Technical Manual
site: bookdown::bookdown_site
documentclass: book
link-citations: yes
---

# Prerequisites

```{r, echo=FALSE}
library(dplyr)
library(bookdown)
library(knitr)
library(kableExtra)

#library(abind)
#library(png)
#library(grid)
#library(fontawesome)

# or the development version
# devtools::install_github("rstudio/bookdown")
# knitr::opts_chunk$set(fig.width = 8, collapse = TRUE, echo=FALSE)
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

```{r, echo=FALSE}
colorize <- function(color, x) {
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, 
      x)
  } else x
}
```

```{r, include=FALSE}
  sys.source("R/code.R", envir = knitr::knit_global())
```

INICIO