# Conceptos generales

Mas que pensar el trading como la accion de comprar y luego vender preferimos verlo como operaciones en las que tomamos posicion en una determinada moneda por un determinado motivo y en algun momento deshacemos esa operacion.


## Pares de monedas

Cada que se realiza una operación se necesitan dos monedas, una origen y una destino; esto es lo que se conoce como __currency pair__ y se especifica separando las dos monedas con un __slash__ (/): **BASE/COUNTER**

Un par de monedas es una notacion diadica que indica el valor relativo de una moneda contra la otra. La moneda que se usa como objetivo se suele denominar __counter__ o __quote__ y la moneda sobre la que se opera se denomina __base__ o __transaction__

Ejemplo:

Cuando se dice EUR/USD = 1.25 lo que se esta diciendo es que, por cada 1.00 de Euros (EUR) obtengo 1.25 Dolares americanos (USD)

Matematicamente se puede ver como:

$${
\begin{aligned}
    n \frac{Base}{Counter} &= Exchange \\
    n * Base &= Exchange * Counter \\
    Usando el ejemplo anterior y n = 1 \\
    1 \frac{Eur}{USD} = 1.25 \\
    1 Eur &= (1 USD) * 1.25


\end{aligned}
}$$

Notese que los pares son intercambiables:

$${
   Si EUR/USD = 1.25 \implies (EUR/USD)^{-1} = USD/EUR = 1.25^{-1} = 0.8
}$$
Informalmente se puede ver como:

> Con una unidad de BASE ¿Qué cantidad de COUNTER obtengo?

### Operaciones

UNa vez establecido un cambio para un par de monedas

La compra se establece como: "Compro N unidades de COUNTER pagando un precio de M BASE por cada uno"
La venta  se establece como: "Vendo  N unidades de COUNTER a un precio de M BASE cada uno"

A currency pair is the dyadic quotation of the relative value of a currency unit against the unit of another currency in the foreign exchange market. The currency that is used as the reference is called the counter currency, quote currency or currency[1] and the currency that is quoted in relation is called the base currency or transaction currency.

Currency pairs are generally written by concatenating the ISO currency codes (ISO 4217) of the base currency and the counter currency, and then separating the two codes with a slash. Alternatively the slash may be omitted, or replaced by either a dot or a dash. A widely traded currency pair is the relation of the euro against the US dollar, designated as EUR/USD. The quotation EUR/USD 1.2500 means that one euro is exchanged for 1.2500 US dollars. Here, EUR is the base currency and USD is the quote currency (counter currency). This means that 1 Euro can be exchangeable to 1.25 US Dollars.

The most traded currency pairs in the world are called the Majors. They involve the currencies euro, US dollar, Japanese yen, pound sterling, Australian dollar, Canadian dollar, and the Swiss franc. 


The quote currency, commonly known as "counter currency," is the second currency in both a direct and indirect currency pair and is used to determine the value of the base currency. In a direct quote, the quote currency is the foreign currency, while in an indirect quote, the quote currency is the domestic currency. Quote currency is also referred to as the "secondary currency." 

1.- BID
    Grabo la operacion
    Actualiza disponible
2.1.- Acepta
    Actualizar estado
    Ajustar posicion
    Grabar flujos (compra, comision, gas)
    Alerta para revisar cuando se ha ejecutado
2.2 Despues de aceptar se debe ejecutar (puede tardar dias)    
    Entonces esta cerrada
    
    
## Logica

Una operacion se abre con una idea, por ejemplo, ganar el 5%
1. Se solicita (se graba en el sistema)
   1.1 Se graba en operaciones
2. Se ejecuta si se cumple la oferta o se cancela

3. Si se ejecuta se incurren en gastos
4. y se generan los flujos

### Compra

1. Se genera la orden en operaciones
2. Se ajusta el saldo (disponible)
3. Se acepta la operacion o se rechaza
3.1 Se acepta
3.1.1 Se actualiza la operacion
3.1.2 Se generan los flujos asociados
3.1.3 Se actualizan los saldos (disponible y real)
3.2 Se rechaza
3.2.1 Se actualiza la operacion
3.2.1 Se actualizan los saldos
