## Paneles laterales 

A diferencia de los estilos actuales que tienden a poner el menú en un panel lateral con un icono en la parte superior, podemos tener dos paneles laterales, a la izquierda y a la derecha.

Particularmente, estoy en contra del icono de barritas por que considero que si algo cambia el estado de la pagina debe indicarlo, por lo que prefiero utilizar un simbolo **">"** para indicar que se realiza una acción (algo que irá de izquierda a derecha) y **"<"** para indicar como se puede deshacer la acción.

Este comportamiento lo logramos de la siguiente manera:

### Page Header

En la cabecera de la aplicacion gestionamos los dos botones

```
    ....
    shiny::tags$span( id="left_side_closed"
                     ,class="yata_side_open"
                     ,shiny::icon("chevron-right fa-lg", style="padding-top: 12px"))
   ,shiny::tags$span( id="left_side_open"
                     ,class="yata_side_closed"
                     ,shiny::icon("chevron-left fa-lg", style= "padding-top: 12px"))
   ...
```

### javascript

Creamos un listener para getionar la acción cuando se hace click sobre esos iconos:

`_listenerSidebarLeft: function(evt)`


### Casos de uso

Ahora nos encontramos con la forma de gestionar el correcto funcionamiento.
El indicador de panel lateral aparece en la barra de menu y es común a todas las página pero, por un lado cada página puede tener o no panel lateral izquierdo y/o panel lateral derecho.

Por otro lado, el usuario activa un panel en una página, el icono cambia de **>** a **<**, y si ahora cambia a otra página con panel lateral, el icono debería ponerse a **>**, o mas correctamente al estado actual del panel **en esa página**. Dicho de otro modo, necesitamos un sistema de memoria que mantenga el estado de cada página y que se actualice en función de la pagina activa.

El metodo implementado es el siguiente:

1. Cada página tiene un objeto panel asociado, y asumimos que sabemos, en tiempo de diseño, si esa página tiene 0,1 o 2 paneles laterales.
2. Cada vez que se crea un panel; es decir, cada vez que se carga una página por primera vez, el panel envia al cliente una estructura con los datos de diseño de la pagina:

```
enum state = {-1,0,1} //Cerrado, no existe, abierto
struct {
   char name;
   char id;
   state left; 
   state right; 
}

```

3. La aplicación almacena esa información en un __set__
4. Cada vez que se activa una página concreta, incluyendo el momento de creación:
    1. Si hay una pagina activa, se almacena
    2. Se indica a la aplicación que la marca como pagina activa
5. En función de los estados de `left` y `right` pone los iconos de las barras en su estado correcto
6. Cuando se detecta un click sobre alguno de los iconos, se actualiza el estado correspondiente