
DELETE FROM CURRENCIES;

INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 500, 1, 6, "1CR"        , "1Credit"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 501, 1, 6, "ABY"        , "ArtByte"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 502, 1, 6, "AC"         , "AsiaCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 503, 1, 6, "ACH"        , "AchieveCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 504, 1, 6, "ADN"        , "Aiden"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 505, 1, 6, "AEON"       , "Aeon"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 506, 1, 6, "AERO"       , "CryptoAero"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 507, 1, 6, "AIR"        , "AirToken"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 508, 1, 6, "APH"        , "Aphelion"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 509, 1, 6, "AUR"        , "AuroraCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 510, 1, 6, "AXIS"       , "AxisCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 511, 1, 6, "BALLS"      , "SnowBalls"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 512, 1, 6, "BANK"       , "BANK"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 513, 1, 6, "BBL"        , "BitBlock"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 514, 1, 6, "BBR"        , "BoolBerry"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 515, 1, 6, "BCC"        , "BitConnect"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 516, 1, 6, "BCN"        , "Bytecoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 517, 1, 6, "BDC"        , "Bollywood Coin"                       );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 518, 1, 6, "BDG"        , "BitDegree"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 519, 1, 6, "BELA"       , "BELA Coin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 520, 1, 6, "BITS"       , "Bitstart"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 521, 1, 6, "BLK"        , "Black Coin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 522, 1, 6, "BLOCK"      , "Block Net"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 523, 1, 6, "BLU"        , "BlueCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 524, 1, 6, "BNS"        , "BonusCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 525, 1, 6, "BONES"      , "Bones Cryptocoin"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 526, 1, 6, "BOST"       , "BoostCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   1, 1, 6, "BTC"        , "Bitcoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 528, 1, 6, "BTCD"       , "Bitcoin Dark"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 529, 1, 6, "BTCS"       , "Bitcoin Shop"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 530, 1, 6, "BTM"        , "Bytom"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 531, 1, 6, "BTS"        , "Bitshares"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 532, 1, 6, "BURN"       , "BURN Cryptocoin"                      );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 533, 1, 6, "BURST"      , "Burst Cryptocoin"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 534, 1, 6, "C2"         , "Coin 2.1"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 535, 1, 6, "CACH"       , "CacheCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 536, 1, 6, "CAI"        , "CAI Token"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 537, 1, 6, "CC"         , "CyberCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 538, 1, 6, "CCN"        , "CannaCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 539, 1, 6, "CGA"        , "Cryptografic Anomaly"                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 540, 1, 6, "CHA"        , "ChanceCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 541, 1, 6, "CINNI"      , "CinniCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 542, 1, 6, "CLAM"       , "Clams"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 543, 1, 6, "CNL"        , "ConcealCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 544, 1, 6, "CNMT"       , "CNMT"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 545, 1, 6, "CNOTE"      , "CryptoNote"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 546, 1, 6, "COMM"       , "COMM"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 547, 1, 6, "CON"        , "PayCon"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 548, 1, 6, "CORG"       , "CorgiCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 549, 1, 6, "CRYPT"      , "CryptCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 550, 1, 6, "CURE"       , "CureCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 551, 1, 6, "CYC"        , "Cycling Coin"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 552, 1, 6, "DGB"        , "DigiByte"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 553, 1, 6, "DICE"       , "Etheroll"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 554, 1, 6, "DIEM"       , "Carpe Diem Coin"                      );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 555, 1, 6, "DIME"       , "Dime Coin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 556, 1, 6, "DIS"        , "Distrocoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 557, 1, 6, "DNS"        , "DNSCrypt"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 558, 1, 6, "DOGE"       , "DogeCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 559, 1, 6, "DASH"       , "Dash"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 560, 1, 6, "DRKC"       , "Dark Cash"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 561, 1, 6, "DRM"        , "DreamCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 562, 1, 6, "DSH"        , "Dashcoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 563, 1, 6, "DVK"        , "DvoraKoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 564, 1, 6, "EAC"        , "EarthCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 565, 1, 6, "EBT"        , "Ebittree Coin"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 566, 1, 6, "ECC"        , "ECC Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 567, 1, 6, "EFL"        , "e-Gulden"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 568, 1, 6, "EMC2"       , "Einsteinium"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 569, 1, 6, "EMO"        , "Emoticoint"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 570, 1, 6, "ENC"        , "EntropyCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 571, 1, 6, "eTOK"       , "eTOK"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 572, 1, 6, "EXE"        , "ExeCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 573, 1, 6, "FAC"        , "FAC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 574, 1, 6, "FCN"        , "FantomCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 575, 1, 6, "FIBRE"      , "FIBRE Cryptocoin"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 576, 1, 6, "FLAP"       , "FlappyCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 577, 1, 6, "FLDC"       , "FoldingCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 578, 1, 6, "FLT"        , "FlutterCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 579, 1, 6, "FOX"        , "FoxCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 580, 1, 6, "FRAC"       , "FractalCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 581, 1, 6, "FRK"        , "Franko"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 582, 1, 6, "FRQ"        , "FairQuark"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 583, 1, 6, "FVZ"        , "FVZCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 584, 1, 6, "FZ"         , "Frozen"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 585, 1, 6, "FZN"        , "Fuzon"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 586, 1, 6, "GAP"        , "GapCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 587, 1, 6, "GDN"        , "Global Denomination"                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 588, 1, 6, "GEMZ"       , "GetGems"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 589, 1, 6, "GEO"        , "GeoCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 590, 1, 6, "GIAR"       , "GIAR"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 591, 1, 6, "GLB"        , "Globe"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 592, 1, 6, "GAME"       , "GameCredits"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 593, 1, 6, "GML"        , "Game League Coin"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 594, 1, 6, "GNS"        , "Gnosis"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 595, 1, 6, "GOLD"       , "Crypto-Gold"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 596, 1, 6, "GPC"        , "GROUPCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 597, 1, 6, "GPUC"       , "GPUCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 598, 1, 6, "GRCX"       , "Gridcoin Classic"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 599, 1, 6, "GRS"        , "GroestlCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 600, 1, 6, "GUE"        , "GUE"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 601, 1, 6, "H2O"        , "Hidrominer"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 602, 1, 6, "HIRO"       , "HIRO"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 603, 1, 6, "HOT"        , "HOT"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 604, 1, 6, "HUC"        , "HUC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 605, 1, 6, "HVC"        , "HVC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 606, 1, 6, "HYP"        , "HYP"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 607, 1, 6,  "HZ"        , "HZ"                                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 608, 1, 6, "IFC"        , "IFC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 609, 1, 6, "ITC"        , "ITC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 610, 1, 6, "IXC"        , "IXC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 611, 1, 6, "JLH"        , "JLH"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 612, 1, 6, "JPC"        , "JPC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 613, 1, 6, "JUG"        , "JUG"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 614, 1, 6, "KDC"        , "KDC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 615, 1, 6, "KEY"        , "KEY"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 616, 1, 6, "LC"         , "LC"                                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 617, 1, 6, "LCL"        , "LCL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 618, 1, 6, "LEAF"       , "LEAF"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 619, 1, 6, "LGC"        , "LGC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 620, 1, 6, "LOL"        , "LOL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 621, 1, 6, "LOVE"       , "LOVE"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 622, 1, 6, "LQD"        , "LQD"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 623, 1, 6, "LTBC"       , "LTBC"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   5, 1, 6, "LTC"        , "Litecoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 625, 1, 6, "LTCX"       , "LTCX"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 626, 1, 6, "MAID"       , "MaidSafeCoin"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 627, 1, 6, "MAST"       , "MAST"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 628, 1, 6, "MAX"        , "MAX"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 629, 1, 6, "MCN"        , "MCN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 630, 1, 6, "MEC"        , "MEC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 631, 1, 6, "METH"       , "METH"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 632, 1, 6, "MIL"        , "MIL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 633, 1, 6, "MIN"        , "MIN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 634, 1, 6, "MINT"       , "MINT"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 635, 1, 6, "MMC"        , "MMC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 636, 1, 6, "MMNXT"      , "MMNXT"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 637, 1, 6, "MMXIV"      , "MMXIV"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 638, 1, 6, "MNTA"       , "MNTA"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 639, 1, 6, "MON"        , "MON"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 640, 1, 6, "MRC"        , "MRC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 641, 1, 6, "MRS"        , "MRS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 642, 1, 6, "OMNI"       , "OMNI"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 643, 1, 6, "MTS"        , "MTS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 644, 1, 6, "MUN"        , "MUN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 645, 1, 6, "MYR"        , "MYR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 646, 1, 6, "MZC"        , "MZC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 647, 1, 6, "N5X"        , "N5X"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 648, 1, 6, "NAS"        , "NAS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 649, 1, 6, "NAUT"       , "NAUT"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 650, 1, 6, "NAV"        , "NAV"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 651, 1, 6, "NBT"        , "NBT"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 652, 1, 6, "NEOS"       , "NEOS"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 653, 1, 6, "NL"         , "NL"                                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 654, 1, 6, "NMC"        , "NMC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 655, 1, 6, "NOBL"       , "NOBL"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 656, 1, 6, "NOTE"       , "NOTE"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 657, 1, 6, "NOXT"       , "NOXT"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 658, 1, 6, "NRS"        , "NRS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 659, 1, 6, "NSR"        , "NSR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 660, 1, 6, "NTX"        , "NTX"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 661, 1, 6, "NXT"        , "NXT Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 662, 1, 6, "NXTI"       , "NXTI"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 663, 1, 6, "OPAL"       , "OPAL"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 664, 1, 6, "PAND"       , "PAND"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 665, 1, 6, "PAWN"       , "PAWN"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 666, 1, 6, "PIGGY"      , "PIGGY"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 667, 1, 6, "PINK"       , "PINK"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 668, 1, 6, "PLX"        , "PLX"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 669, 1, 6, "PMC"        , "PMC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 670, 1, 6, "POT"        , "POT"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 671, 1, 6, "PPC"        , "PPC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 672, 1, 6, "PRC"        , "PRC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 673, 1, 6, "PRT"        , "PRT"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 674, 1, 6, "PTS"        , "PTS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 675, 1, 6, "Q2C"        , "Q2C"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 676, 1, 6, "QBK"        , "QBK"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 677, 1, 6, "QCN"        , "QCN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 678, 1, 6, "QORA"       , "QORA"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 679, 1, 6, "QTL"        , "QTL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 680, 1, 6, "RBY"        , "RBY"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 681, 1, 6, "RDD"        , "ReddCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 682, 1, 6, "RIC"        , "RIC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 683, 1, 6, "RZR"        , "RZR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 684, 1, 6, "SDC"        , "SDC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 685, 1, 6, "SHIBE"      , "SHIBE"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 686, 1, 6, "SHOPX"      , "SHOPX"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 687, 1, 6, "SILK"       , "SILK"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 688, 1, 6, "SJCX"       , "SJCX"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 689, 1, 6, "SLR"        , "SLR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 690, 1, 6, "SMC"        , "SMC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 691, 1, 6, "SOC"        , "SOC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 692, 1, 6, "SPA"        , "SPA"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 693, 1, 6, "SQL"        , "SQL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 694, 1, 6, "SRCC"       , "SRCC"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 695, 1, 6, "SRG"        , "SRG"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 696, 1, 6, "SSD"        , "SSD"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 697, 1, 6, "STR"        , "STR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 698, 1, 6, "SUM"        , "SUM"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 699, 1, 6, "SUN"        , "SUN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 700, 1, 6, "SWARM"      , "SWARM"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 701, 1, 6, "SXC"        , "SXC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 702, 1, 6, "YNC"        , "SYNC"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 703, 1, 6, "SYS"        , "SysCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 704, 1, 6, "TAC"        , "TalkCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 705, 1, 6, "TOR"        , "TORCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 706, 1, 6, "TRUST"      , "Crypto Trust Network"                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 707, 1, 6, "TWE"        , "TWE"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 708, 1, 6, "UIS"        , "Unitus"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 709, 1, 6, "ULTC"       , "Umbrella-LTC"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 710, 1, 6, "UNITY"      , "SuperNET"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 711, 1, 6, "URO"        , "UroCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 712, 1, 6, "USDE"       , "USDe Coin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   8, 1, 6, "USDT"       , "Tether"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 714, 1, 6, "UTC"        , "UltraCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 715, 1, 6, "UTIL"       , "UTIL"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 716, 1, 6, "UVC"        , "UniversityCoin"                       );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 717, 1, 6, "VIA"        , "Viacoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 718, 1, 6, "VOOT"       , "Crypto VOOT"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 719, 1, 6, "VRC"        , "VeriCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 720, 1, 6, "VTC"        , "Vertcoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 721, 1, 6, "WC"         , "WinCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 722, 1, 6, "WDC"        , "WorldCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 723, 1, 6, "WIKI"       , "WIKI"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 724, 1, 6, "WOLF"       , "CryptoWolf"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 725, 1, 6, "X13"        , "X13 Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 726, 1, 6, "XAI"        , "Sapience AIFX"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 727, 1, 6, "XAP"        , "Apollon"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 728, 1, 6, "XBC"        , "Bitcoin Plus"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 729, 1, 6, "XC"         , "XCurrency"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 730, 1, 6, "XCH"        , "ClearingHouse"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 731, 1, 6, "XCN"        , "Crypton,ite"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 732, 1, 6, "XCP"        , "CounterParty"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 733, 1, 6, "XCR"        , "Crypti"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 734, 1, 6, "XDN"        , "DigitalNote"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 735, 1, 6, "XDP"        , "DogeParty"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 736, 1, 6, "XHC"        , "HonorCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 737, 1, 6, "XLB"        , "LibertyCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 738, 1, 6, "XMG"        , "Magi"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 739, 1, 6, "XMR"        , "Monero"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 740, 1, 6, "XPB"        , "PebbleCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 741, 1, 6, "XPM"        , "PrimeCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   3, 1, 6, "XRP"        , "Ripple"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 743, 1, 6, "XSI"        , "StabilityShares"                      );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 744, 1, 6, "XST"        , "Stealth"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 745, 1, 6, "XSV"        , "SilliconValleyCoin"                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 746, 1, 6, "XUSD"       , "CoinoUSD"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 747, 1, 6, "XXC"        , "Creds XXC"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 748, 1, 6, "YACC"       , "YACCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 749, 1, 6, "YANG"       , "YangCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 750, 1, 6, "YC"         , "YellowCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 751, 1, 6, "YIN"        , "YinCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 752, 1, 6, "XVC"        , "VCash"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 753, 1, 6, "FLO"        , "Florin"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 754, 1, 6, "XEM"        , "NEM/XEM"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 755, 1, 6, "ARCH"       , "ARCHCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 756, 1, 6, "HUGE"       , "CryptoHuge"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 757, 1, 6, "GRC"        , "GridCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 758, 1, 6, "IOC"        , "I/O Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 759, 1, 6, "INDEX"      , "INDEX"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   2, 1, 6, "ETH"        , "Ethereum"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 761, 1, 6, "SC"         , "Siacoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 762, 1, 6, "BCY"        , "BitCrystals"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 763, 1, 6, "EXP"        , "Expanse"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 764, 1, 6, "FCT"        , "Factom"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 765, 1, 6, "BITUSD"     , "bitUSD"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 766, 1, 6, "BITCNY"     , "bitCNY"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 767, 1, 6, "RADS"       , "Radium"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 768, 1, 6, "AMP"        , "HyperSpace"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 769, 1, 6, "VOX"        , "Voxels"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 770, 1, 6, "DCR"        , "Decred"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 771, 1, 6, "LSK"        , "Lisk"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 772, 1, 6, "DAO"        , "Decentralized Autonomous Organization");
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 773, 1, 6, "LBC"        , "LBRY Credits"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 774, 1, 6, "STEEM"      , "Steem"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 775, 1, 6, "SBD"        , "Steem Dollars"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 776, 1, 6, "ETC"        , "Ethereum Classic"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 777, 1, 6, "REP"        , "Augur"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 778, 1, 6, "ARDR"       , "ARDR"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 779, 1, 6, "ZEC"        , "ZCash"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 780, 1, 6, "STRAT"      , "Stratis"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 781, 1, 6, "NXC"        , "Nexium"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 782, 1, 6, "PASC"       , "Pascal Coin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 783, 1, 6, "GNT"        , "Golem"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 784, 1, 6, "GNO"        , "Gnosis"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   4, 1, 6, "BCH"        , "Bitcoin Cash"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 786, 1, 6, "ZRX"        , "0x"                                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 787, 1, 6, "CVC"        , "Civic"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 788, 1, 6, "OMG"        , "OmiseGO"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 789, 1, 6, "GAS"        , "GAS Neo"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 790, 1, 6, "STORJ"      , "Decentralized Cloud Storage"          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   6, 1, 6, "EOS"        , "Crypt/EOS"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 792, 1, 6, "USDC"       , "USD Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 793, 1, 6, "SNT"        , "Status"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 794, 1, 6, "KNC"        , "Kyber Network"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 795, 1, 6, "BAT"        , "Basic Attentio Token"                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 796, 1, 6, "LOOM"       , "LOOM Networks"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 797, 1, 6, "QTUM"       , "Qtum"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 798, 1, 6, "BNT"        , "Bancor"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 799, 1, 6, "MANA"       , "Decentraland"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 800, 1, 6, "FOAM"       , "FOAM Protocol"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 801, 1, 6, "BCHABC"     , "Bitcoin Cash ABC"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 802, 1, 6, "BCHSV"      , "Bitcoin SV"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 803, 1, 6, "NMR"        , "Numerate"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 804, 1, 6, "POLY"       , "PolyMath"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 805, 1, 6, "LPT"        , "Livepeer"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 999, 1, 2, "USD"        , "US Dollar"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 998, 1, 2, "EUR"        , "Euro"                                 );