## Tablas

La version actual esta basada en el paquete **reactable**

https://glin.github.io/reactable/

El modulo es: **widgetTable.R**

yuiTable: UI Object


Dado el gran numero de opciones, parece mas razonable crear un sistema de objetos que mantenga la configuracion y que permita la reutilizacion:

1. Creamos una definicion de tabla que sea reutilizable: createTableDef
2. Creamos diferentes funciones para diferentes tipos de tabla


### createTableDef

Recibe el df y un conjunto de parametros:

types: Una secuencia de caracteres indicando el tipo de dato de la columna
    a - amount
    b - button
    i - entero
    l - label
    n - number
    s - string
    p - porcentage de forma 0,xx
    P - porcentage en fomato xx,xx
    d - date
    h - hour
    m - tms
    v - value - Ajusta los decimales
    n - number
    x/space placeholder

title: Nombre de las columnas como secuencia de caracteres

target
event

#   u - Upper case
#   l - Lower Case
#   a - as is
#   h - Hidden
#   x/sp placeholder
#   defecto title case

