---
title: "Exponential moving average (EMA)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exponential moving average (EMA)

Calculates an exponentially-weighted mean, giving more weight to recent observations

The Exponential Moving Average is a staple of technical analysis and is used in countless technical indicators. In a Simple Moving Average, each value in the time period carries equal weight, and values outside of the time period are not included in the average. However, the Exponential Moving Average is a cumulative calculation, including all data. Past values have a diminishing contribution to the average, while more recent values have a greater contribution. This method allows the moving average to be more responsive to changes in the data.


The EMA result is initialized with the n-period sample average at period n. The exponential decay is applied from that point forward.

## Formula


$$
\begin{aligned}
 wilder=T \implies K = \frac{2}{(n+1)} \\
 wilder=F \implies K = \frac{1}{n} \\
 EMA = EMA_{[-1]} + K (v(i) - EMA_[-1])
\end{aligned}
$$

## Parametros

__n__

The Window Size is nothing but the look back period and this forms the basis of your ALMA settings.


__wilder__

Set the value of K

