## Datos de sesion

Nos referimos a los datos de sesion a los datos en "tiempo real" mientras estamos ejecutando la aplicacion.

En principio son datos que nos interesan durante la sesion y por lo tanto temporales. Dicho de otro modo, si empezamos una sesion nos interesa saber como va evolucionando el activo durante la sesion y despues no es relevante.

Originalmente los datos se iban recuperando en segundo plano mientras la sesion esa activa, pero si existen varias sesiones se produciria una duplicacion de los datos por lo que el metodo debe ser en modo singleton.

La idea principal es:

- Cuando un cliente se conecta arranca un demonio que recoge los datos actuales periodicamente
- Cuando el cliente se desconecta se para el demonio

Pero si se conecta un cliente y el demonio esta arrancado no debe pasar nada
Si nos desconectamos y nos volvemos a conectar una hora despues, deberiamos tener los datos de esa hora
Desde el punto de vista historico, los datos a mostrar deberian ser desde un cierto momento respecto de ahora; es decir

**la tabla se debe limpiar periodicamente**


### Enfoque

- Creamos un servidor (yata_mqsrv) que se encargara periodicamente de cargar los datos de la sesion
- Creamos un cliente  (yata_mqcli) que se encarga de notificar al servidor que un cliente se ha conectado o desconectado

Podriamos crear un solo ejecutable con fork, pero entonces como sabriamos los parametros del padre y del hijo?
Lo hacemos con un fork y luego un execcvp o similar
O sea, el cliente escribe en la cola
si no existe el servidor, lo crea y lo arranca cpn el fork que hace el exec
y si no hay parametros pues crea el servidor y punto


- La comunicacion se hace por una cola de modo que se serializen las llamadas
- El cliente chequea si el servidor esta activo, si no lo activa
- El intervalo de chequeo y el tiempo de espera es parametrizable

Al iniciar la aplicacion, hacemos una peticion REST al servidor, este arranca los procesos
Creamos el evento disconnect basado en los eventos:

- shiny:connected
- shiny:sessioninitialized
- shiny:disconnected

y el javascript:

$(document).on('shiny:value', function(event) {
  event.preventDefault();
});
