# WEB Componentes

Shiny esta basado en Boostrap y ofrece una funcionalidad "suficiente". Sobre Shiny se han construido una multitud de paquetes que permiten un look and feel mas sofisticado. El problema viene cuando se empiezan a mezclar dos o mas de esos paquetes, por ejemplo, shinydashboardplus y shinywidgets, el primero depende de shinydashboard con lo que tenemos tres paquetes cargados con su correspondientes estilos y codigo javascript, lo cual, dependiendo de la calidad y del estilo de cada paquete puede dar lugar a conflictos de nombres, reduccion de funcionalidad, etc.

Por otro lado, cada pagina Web la podemos ver como un conjunto de widgets mas o menos complejos


El sistema utiliza el siguiente criterio:

- Todos los componentes Web estan encapsulados en una parte de diseño y otro de servidor para interactuar con el
- Los componentes de diseño se denominan yui_Nombre_
- Los componentes de servidor se denominan upd_Nombre_

De esta manera, se encapsulan los componentes de los diferentes paquetes y solo existe un punto de cambio para cada widget.
Por ejemplo, hemos elegido utilizar los botones de shinyBS, que usan la funcion bsButton y en los parametros se configura el estilo, tamaño, etc.

Primero creamos un widget yuiButton que encapsula a bsButton.
Creamos un conjunto de _wrappers_ yuiButtonXXX que introducen ciertos parametros por defecto
Cada uno de estos _wrappers_ invoca en ultima instancia a yuiButton que hace la llamada a bsButton.

Si deseamos cambiar los botones de bsButton por otro estilo, basta con modificar la funcion **yuiButton**