# DATATABLE

El problema de datatable es que usa unos estilos que crea dinamicamente
se pueden saltar si se usa _style=auto_ y existe un tema **bslib** pero me ha fallado en el paquete (aunque me funcionaba en el codigo fuente)

Por otro lado necesitamos diferentes tipos de tablas (moendas, posiciones,datos, etc)

## Solucion
- Creamos una instancia propia de DT (lease, clonamos el codigo): YATADataTable
- Añadimos un parametro nuevo a renderDataTable: **type**. es el que no dara los estilos personalizados
- Los estilos de cada tipo se definen en bslib como `table.display.__type__ items` 

Siempre podemos usar DT

## Samples

Opciones de tabla:

- tickers: Informacion de cotiaciones
- accounts: Informacion de cuentas
...

## Implementacion

1. Simplemente replicar el codigo de DT desde: `https://github.com/rstudio/DT.git`
2. Cmabiar la funcion renderDatatable de datatables.R a YATARenderDataTable
2. Modificar DESCRIPTION: `Package: YATADataTable`
3. Modificar NAMESPACE para exportar el nuevo nombre de renderdata table
3. en datatables.R, funcion datatable, añadir el parametro `type=NULL`
4. en shiny.R cambiar enderDataTable por YATARenderDataTable (para que se exporte)
5. Crear los estilos table.display.xxx cosas


