## Hyper-V

1. Crear una red NAT
2. Conectar las maquinas virtuales a la red

### NAT

Para asignar una IP fija a cada maquina virtual creamos una red NAT

En Powershell como administrador, crear un nuevo Switch con el comando New-VMSwitch

https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network


https://docs.microsoft.com/en-us/powershell/module/hyper-v/new-vmswitch?view=windowsserver2022-ps

1. Crear el nuevo Switch: New-VMSwitch -SwitchName "VMNat" -SwitchType Internal
2. Chequear obteniendo el ifIndex: Get-NetAdapter (en este caso 73)
3. Configurar el Gateway en funcion del numero de IP/maquinas a mapear

255.255.255.0/24

New-NetIPAddress -IPAddress 192.168.0.1 -PrefixLength 24 -InterfaceIndex 73

4. Configurar la red NAT

Name es el nombre de la Red para borrarla

New-NetNat -Name <NATOutsideName> -InternalIPInterfaceAddressPrefix <NAT subnet prefix>
New-NetNat -Name DamienNAT -InternalIPInterfaceAddressPrefix 192.168.0.0/24

### Conectar maquinas

WinNAT no asigna direcciones IP a un endpoint (VM) por lo que hay que hacerlo desde la propia maquina virtual

en Ubuntu:

cd /etc/netplan/
sudo nano 01-network-manager-all.yaml

network:
  version: 2
  renderer: networkd  
  ethernets:
    eth0:
      addresses:
      - 192.168.0.2/24
      gateway4: 192.168.0.1
      nameservers:
        addresses:
        - 8.8.8.8
        - 8.8.4.4
      dhcp4: no

Aplicar cambios
dhcp4: yes/no coger la ip del dhcp o no

### Tunning

Tuning Linux File Systems on Dynamic VHDX Files

Some Linux file systems may consume significant amounts of real disk space even when the file system is mostly empty. To reduce the amount of real disk space usage of dynamic VHDX files, consider the following recommendations:

    When creating the VHDX, use 1MB BlockSizeBytes (from the default 32MB) in PowerShell, for example:

Powershell

PS > New-VHD -Path C:\MyVHDs\test.vhdx -SizeBytes 127GB -Dynamic -BlockSizeBytes 1MB

    The ext4 format is preferred to ext3 because ext4 is more space efficient than ext3 when used with dynamic VHDX files.

    When creating the filesystem specify the number of groups to be 4096, for example:

Bash



comment # mkfs.ext4 -G 4096 /dev/sdX1


### host

Crear la entrada en host
