## JGGShiny

Los patrones de paginas los creamos en el paquete JGGShiny
La idea es customizar las paginas que ofrece shiny como templates


## JGGShiny

JGGDashboardFull - Es un dashboard con paneles laterales izquierdo y derecho

### Naming conventions

La version actual de Shiny utiliza bslib, lo que hacemos es copiar las funciones necesarias prefijandolas con shiny_ o bslib_ para distinguir la fuente original y las modificadas como jgg_fuente_


## DashboardFull

Es una web que tiene:
- Una barra de navagacion (menu)
- Cada Pagina tiene una barra lateral derecha y una izquierda


La pagina tiene esta estructura donde cada nombre corresponde a su id

jgg_container Contiene dos "paginas" la normal y la de error fatal
    jgg_page
        jgg_page_header
        jgg_page_main
        jgg_page_footer
   jgg_main_err
        

### Container 
 Tiene dos div:
 - jgg_page     La pagina de datos
 - jgg_main_err La pagina de error general
 
### Page

Tiene 3 divs:

        jgg_header : El menu
        jgg_main   : Los datos
        jgg_footer : El pie


Los recursos estan en jggshiny
y javascript esta en jquery $.jggshiny

### Clases

jgg_container
jgg_page
jgg_header
jgg_body
jgg_footer

jgg_clearfix

| Clase           |    Descripcion                            |
+-----------------+-------------------------------------------+
| jgg_brand       | Clase del titulo                          |
| jgg_side_open   | Gestiona el indicador de panel abierto    |
| jgg_side_close  | Gestiona el indicador de panel cerrado    |
| jgg_nav_left    | Estilo del panel izquierdo                |
| jgg_nav_right   | Estilo del panel derecho                  |

### Javascript

Los gestores en javascript tiran de _data-toggle_

jgg_offcanvas
control_sidebar

