## Shiny

<!--chapter:end:001-shiny.Rmd-->

## Diseño de paginas (layout)

Los bloques que conforman la aplicación Web se asocian con el menú de navegación principal, a su vez, cada bloque puede tener subbloques los cuales se asocian con un menú "superior" secundario el cual, opcionalmente también podría tener otro subbloque al margen de la usabilidad de la usabilidad de esta navegación

Si lo asimilamos a objetos, la estructura es:

XXXX Aqui ponemos la imagen design,uml

Nótese que tanto el contenedor como la pagina puede tener información especifica en los paneles laterales, entendemos que en estos casos el panel lateral del contenedor contiene información que afecta a todas las paginas mientras que los paneles laterales de las páginas contienen información propia de las mismas.

Para gestionar esto, el diseño de la página a nivel contenedor es:
```
prfx-container
   prfx-container-left
   prfx-container-main
   prfx-container-right
```

Donde `prfx` es el id del panel

Para evitar abstracciones y complejidades innecesarias, asumiremos que en tiempo de diseño se conoce si una determinada pagina puede tener un panel lateral con uno o dos componentes, el del "padre" y el propio.

<!--chapter:end:002-design.Rmd-->

## Paquetes Shiny 

Antes de hablar de _Shiny_ y de sus características debemos detenernos brevemente en comprender que es una página Web.

De manera general, y esto aplica a todas las páginas y aplicaciones Web, independientemente del lenguaje utilizado para su generación, una página Web está formada por:

1. Una definición de la página, su estructura y componentes de acuerdo con un lenguaje de marcado: **HTML** o **XHTML**, el cual define los objetos soportados y sus atributos y propiedades.
2. Una definición de estilos que definen como se muestran cada uno de los componentes en función, normalmente, de los diseñadores, el sistema sobre el que se muestra la página y los atributos de este.
3. Un lenguaje de programación: **javascript**, para enriquecer la página con cierto nivel de dinamismo e interacción con el usuario.

XXX Ampliar esto para indicar que a partir de esta base se pueden construir widgets y casi cualquier cosa XXX

### Shiny

_Shiny_ está basado en _Boostrap_, un _front-end_ que ya ofrece _out-of-the-box_ muchos componentes o _widgets_ ya preparados para la creación de la página web.

y ofrece una funcionalidad "suficiente" para la mayoria de las páginas Web dinámicas. 

Sobre _Shiny_ se han construido una multitud de paquetes que permiten un _look and feel_ mas sofisticado. El problema viene cuando se empiezan a mezclar dos o mas de esos paquetes, por ejemplo, shinydashboardplus y shinywidgets, el primero depende de shinydashboard con lo que tenemos tres paquetes cargados con su correspondientes estilos y codigo javascript, lo cual, dependiendo de la calidad y del estilo de cada paquete puede dar lugar a conflictos de nombres, reduccion de funcionalidad, etc.

Por otro lado, cada pagina Web la podemos ver como un conjunto de widgets mas o menos complejos


El sistema utiliza el siguiente criterio:

- Todos los componentes Web estan encapsulados en una parte de diseño y otro de servidor para interactuar con el
- Los componentes de diseño se denominan yui_Nombre_
- Los componentes de servidor se denominan upd_Nombre_

De esta manera, se encapsulan los componentes de los diferentes paquetes y solo existe un punto de cambio para cada widget.
Por ejemplo, hemos elegido utilizar los botones de shinyBS, que usan la funcion bsButton y en los parametros se configura el estilo, tamaño, etc.

Primero creamos un widget yuiButton que encapsula a bsButton.
Creamos un conjunto de _wrappers_ yuiButtonXXX que introducen ciertos parametros por defecto
Cada uno de estos _wrappers_ invoca en ultima instancia a yuiButton que hace la llamada a bsButton.

Si deseamos cambiar los botones de bsButton por otro estilo, basta con modificar la funcion **yuiButton**

<!--chapter:end:010-wrappers.Rmd-->

# WEB

En esta seccion estan las cosas que se deberian implementar, mejorar, etc.
Cuando alguna de ellas se realice, normalment pasara al apartado de decisiones

("../images/webpackages.png") 

## Tablas de Datos

La clase base deberia incoprorar metodos para inserta y actualizar datos
Para el Update por ejemplo
update(list(campos), list(where))

## Arquitectura

La aplicacion Web esta basada en modulos y sub modulos

## Nomenclatura

prefijos:

+---------+-----------------------------------------------------------------+
| Prefijo |  Descripcion  |
+------+-----------------------------------------------------------------+
| mod  |  Indica que es una pagina de un panel |
| frm  |  Indica que es un formulario que se mostrara dentro de un panel |
+------+-----------------------------------------------------------------+

+---------+-----------------------------------------------------------------+
| Sufijo  |  Descripcion  |
+---------+-----------------------------------------------------------------+
| Input   |  Contiene la interfaz de usuario |
| Server  |  Contiene el codigo asociado |
+---------+-----------------------------------------------------------------+

Los modulos, formularios, etc. **se ejecutan de manera dinamica**  por lo que si no se sigue la nomenclatura el sistema fallará.


## Creacion de componentes


<!--chapter:end:0501-commarea.Rmd-->

# WEB

En esta seccion estan las cosas que se deberian implementar, mejorar, etc.
Cuando alguna de ellas se realice, normalment pasara al apartado de decisiones

##### ("../images/webpackages.png") 

## Tablas de Datos

La clase base deberia incoprorar metodos para inserta y actualizar datos
Para el Update por ejemplo
update(list(campos), list(where))

## Arquitectura

La aplicacion Web esta basada en modulos y sub modulos

## Nomenclatura

prefijos:

+---------+-----------------------------------------------------------------+
| Prefijo |  Descripcion  |
+------+-----------------------------------------------------------------+
| mod  |  Indica que es una pagina de un panel |
| frm  |  Indica que es un formulario que se mostrara dentro de un panel |
+------+-----------------------------------------------------------------+

+---------+-----------------------------------------------------------------+
| Sufijo  |  Descripcion  |
+---------+-----------------------------------------------------------------+
| Input   |  Contiene la interfaz de usuario |
| Server  |  Contiene el codigo asociado |
+---------+-----------------------------------------------------------------+

Los modulos, formularios, etc. **se ejecutan de manera dinamica**  por lo que si no se sigue la nomenclatura el sistema fallará.


## Creacion de componentes


<!--chapter:end:0501-web.Rmd-->

## Javascript

Tenemos varios tipo de código javascript:

- Código que se debe ejecutar al cargar la pagina
- Propio para el funcionamiento de la pagina
- Mensajes personalizados para la comunicación shiny/web
- Mensajes para enviar notificaciones al servidor
- Funciones que resultan "natural" que estén integradas con shiny


### yata.js

Este módulo tiene por función ejecutarse cada vez que se carga la página.
Su función es inicializar el entorno y se debe ejecutar cuando la página está cargada; dicho de otro modo, el código debe incluirse al final de la pagina

**importante** es donde debe instanciarse el objeto YATAApp como YATA

### YATAApp.js

Este módulo define la clase `YATAApp` que contiene el código específico de la aplicación.
Para evitar problemas de nombres, todo nuestro código se encapsula en esta clase y se instancia con el nombre fijo **YATA**

En caso de necesitar utilizar otro nombre, por el motivo que sea, es necesario:

1. Modificar el modulo `yata.js` instanciando la clase con el objeto deseado
2. Modificar la constante `YATAWEBDEF$jsapp` con el nuevo valor
3. Regenerar los paquetes: `YATAWebCore`

### extendShinyjs

Esta función permite integrar nuestras propias funciones javascript en el objeto `js` de shiny.

La información de uso esta disponible en [extendShinyjs](https://www.rdocumentation.org/packages/shinyjs/versions/2.0.0/topics/extendShinyjs)

<!--chapter:end:900-js.Rmd-->

## CSS

XXX

### Modulos

yataAdminLTE.css esta sobreescrito

### CSS/Javascript

Estas clases se usan en el código javascript:

- **yata_leftside_open**
- **yata_leftside_closed**
- **yata_side_closed**  Gestiona la visibilidad del indicador de panel lateral
- **yata_side_noside**  Gestiona la visibilidad del indicador de panel lateral

<!--chapter:end:901-css.Rmd-->

