-- Usuarios
CREATE USER 'YATA'@'localhost' IDENTIFIED BY 'yata';
GRANT ALL PRIVILEGES ON YATA.*          TO 'YATA'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON YATABase.*      TO 'YATA'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON YATAData.*      TO 'YATA'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON YATASimm.*      TO 'YATA'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON YATATest.*      TO 'YATA'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON YATATemplate.*  TO 'YATA'@'localhost' WITH GRANT OPTION;