DROP TABLE  IF EXISTS SESSION_EXCHANGES CASCADE;
CREATE TABLE SESSION_EXCHANGES  (
    BASE     VARCHAR(10)  NOT NULL -- Camara
   ,COUNTER  VARCHAR(10) NOT NULL -- Moneda evaluada
   ,TMS      DATE        NOT NULL         
   ,CLOSE    DOUBLE      NOT NULL         
   ,PRIMARY KEY ( BASE, COUNTER, TMS DESC )
);

DROP TABLE  IF EXISTS SESSION_CONTROL CASCADE;
CREATE TABLE SESSION_CONTROL  (
    CLEARING VARCHAR(8)  NOT NULL -- Camara
   ,BASE     VARCHAR(10) NOT NULL -- Moneda base
   ,COUNTER  VARCHAR(10) NOT NULL -- Moneda evaluada
   ,SESSION01 TIMESTAMP
   ,SESSION02 TIMESTAMP   
   ,SESSION04 TIMESTAMP   
   ,SESSION08 TIMESTAMP   
   ,SESSION24 TIMESTAMP   
   ,PRIMARY KEY ( CLEARING, BASE, COUNTER )
);

-- Tabla general de SESSION
DROP TABLE  IF EXISTS SESSION_BASE CASCADE;
CREATE TABLE SESSION_BASE  (
    CLEARING VARCHAR(8)  NOT NULL -- Camara
   ,TMS      TIMESTAMP   NOT NULL     
   ,BASE     VARCHAR(10) NOT NULL -- Moneda base
   ,COUNTER  VARCHAR(10) NOT NULL -- Moneda evaluada
   ,OPEN     DOUBLE      NOT NULL 
   ,CLOSE    DOUBLE      NOT NULL 
   ,HIGH     DOUBLE      NOT NULL 
   ,LOW      DOUBLE      NOT NULL 
   ,VOLUME   DOUBLE      NOT NULL 
   ,AVERAGE  DOUBLE      NOT NULL 
   ,PRIMARY KEY ( CLEARING, TMS DESC, BASE, COUNTER )
);


-- Cada tabla se llama SESSIONin - i Intervalo - n Periodos
-- SESSION mensuales
-- DROP TABLE  IF EXISTS SESSION_POL_M1 CASCADE;
-- CREATE TABLE SESSION_POL_M1 LIKE SESSION_BASE;
-- 
-- -- SESSION Semanales
-- DROP TABLE  IF EXISTS SESSION_POL_W1 CASCADE;
-- CREATE TABLE SESSION_POL_W1 LIKE SESSION_BASE;

-- SESSION Diarios
DROP TABLE  IF EXISTS SESSION_01 CASCADE;
CREATE TABLE SESSION_01 LIKE SESSION_BASE;
DROP TABLE  IF EXISTS SESSION_02 CASCADE;
CREATE TABLE SESSION_02 LIKE SESSION_BASE;
DROP TABLE  IF EXISTS SESSION_04 CASCADE;
CREATE TABLE SESSION_04 LIKE SESSION_BASE;
DROP TABLE  IF EXISTS SESSION_08 CASCADE;
CREATE TABLE SESSION_08 LIKE SESSION_BASE;
DROP TABLE  IF EXISTS SESSION_24 CASCADE;
CREATE TABLE SESSION_24 LIKE SESSION_BASE;

-- SESSION Horarios
-- En funcion de las horas que da poloniex

-- DROP TABLE  IF EXISTS SESSION_POL_H2 CASCADE;
-- CREATE TABLE SESSION_POL_H2 LIKE SESSION_BASE;
-- 
-- DROP TABLE  IF EXISTS SESSION_POL_H4 CASCADE;
-- CREATE TABLE SESSION_POL_H4 LIKE SESSION_BASE;
-- 
-- DROP TABLE  IF EXISTS SESSION_POL_H8 CASCADE;
-- CREATE TABLE SESSION_POL_H8 LIKE SESSION_BASE;

