
DELETE FROM CURRENCIES;

INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 500,  0,  6, "1CR"        , "1Credit"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 501,  0,  6, "ABY"        , "ArtByte"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 502,  0,  6, "AC"         , "AsiaCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 503,  0,  6, "ACH"        , "AchieveCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 504,  0,  6, "ADN"        , "Aiden"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 505,  0,  6, "AEON"       , "Aeon"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 506,  0,  6, "AERO"       , "CryptoAero"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 507,  0,  6, "AIR"        , "AirToken"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 508,  0,  6, "APH"        , "Aphelion"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 509,  0,  6, "AUR"        , "AuroraCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 510,  0,  6, "AXIS"       , "AxisCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 511,  0,  6, "BALLS"      , "SnowBalls"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 512,  0,  6, "BANK"       , "BANK"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 513,  0,  6, "BBL"        , "BitBlock"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 514,  0,  6, "BBR"        , "BoolBerry"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 515,  0,  6, "BCC"        , "BitConnect"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 516,  0,  6, "BCN"        , "Bytecoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 517,  0,  6, "BDC"        , "Bollywood Coin"                       );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 518,  0,  6, "BDG"        , "BitDegree"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 519,  0,  6, "BELA"       , "BELA Coin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 520,  0,  6, "BITS"       , "Bitstart"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 521,  0,  6, "BLK"        , "Black Coin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 522,  0,  6, "BLOCK"      , "Block Net"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 523,  0,  6, "BLU"        , "BlueCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 524,  0,  6, "BNS"        , "BonusCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 525,  0,  6, "BONES"      , "Bones Cryptocoin"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 526,  0,  6, "BOST"       , "BoostCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   1,  1,  6, "BTC"        , "Bitcoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 528,  0,  6, "BTCD"       , "Bitcoin Dark"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 529,  0,  6, "BTCS"       , "Bitcoin Shop"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 530,  0,  6, "BTM"        , "Bytom"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 531,  0,  6, "BTS"        , "Bitshares"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 532,  0,  6, "BURN"       , "BURN Cryptocoin"                      );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 533,  0,  6, "BURST"      , "Burst Cryptocoin"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 534,  0,  6, "C2"         , "Coin 2.1"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 535,  0,  6, "CACH"       , "CacheCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 536,  0,  6, "CAI"        , "CAI Token"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 537,  0,  6, "CC"         , "CyberCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 538,  0,  6, "CCN"        , "CannaCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 539,  0,  6, "CGA"        , "Cryptografic Anomaly"                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 540,  0,  6, "CHA"        , "ChanceCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 541,  0,  6, "CINNI"      , "CinniCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 542,  0,  6, "CLAM"       , "Clams"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 543,  0,  6, "CNL"        , "ConcealCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 544,  0,  6, "CNMT"       , "CNMT"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 545,  0,  6, "CNOTE"      , "CryptoNote"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 546,  0,  6, "COMM"       , "COMM"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 547,  0,  6, "CON"        , "PayCon"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 548,  0,  6, "CORG"       , "CorgiCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 549,  0,  6, "CRYPT"      , "CryptCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 550,  0,  6, "CURE"       , "CureCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 551,  0,  6, "CYC"        , "Cycling Coin"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 552,  0,  6, "DGB"        , "DigiByte"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 553,  0,  6, "DICE"       , "Etheroll"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 554,  0,  6, "DIEM"       , "Carpe Diem Coin"                      );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 555,  0,  6, "DIME"       , "Dime Coin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 556,  0,  6, "DIS"        , "Distrocoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 557,  0,  6, "DNS"        , "DNSCrypt"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 558,  0,  6, "DOGE"       , "DogeCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 559,  0,  6, "DASH"       , "Dash"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 560,  0,  6, "DRKC"       , "Dark Cash"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 561,  0,  6, "DRM"        , "DreamCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 562,  0,  6, "DSH"        , "Dashcoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 563,  0,  6, "DVK"        , "DvoraKoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 564,  0,  6, "EAC"        , "EarthCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 565,  0,  6, "EBT"        , "Ebittree Coin"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 566,  0,  6, "ECC"        , "ECC Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 567,  0,  6, "EFL"        , "e-Gulden"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 568,  0,  6, "EMC2"       , "Einsteinium"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 569,  0,  6, "EMO"        , "Emoticoint"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 570,  0,  6, "ENC"        , "EntropyCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   2,  1,  6, "ETH"        , "Ethereum"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 571,  0,  6, "eTOK"       , "eTOK"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 572,  0,  6, "EXE"        , "ExeCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 573,  0,  6, "FAC"        , "FAC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 574,  0,  6, "FCN"        , "FantomCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 575,  0,  6, "FIBRE"      , "FIBRE Cryptocoin"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 576,  0,  6, "FLAP"       , "FlappyCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 577,  0,  6, "FLDC"       , "FoldingCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 578,  0,  6, "FLT"        , "FlutterCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 579,  0,  6, "FOX"        , "FoxCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 580,  0,  6, "FRAC"       , "FractalCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 581,  0,  6, "FRK"        , "Franko"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 582,  0,  6, "FRQ"        , "FairQuark"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 583,  0,  6, "FVZ"        , "FVZCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 584,  0,  6, "FZ"         , "Frozen"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 585,  0,  6, "FZN"        , "Fuzon"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 586,  0,  6, "GAP"        , "GapCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 587,  0,  6, "GDN"        , "Global Denomination"                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 588,  0,  6, "GEMZ"       , "GetGems"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 589,  0,  6, "GEO"        , "GeoCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 590,  0,  6, "GIAR"       , "GIAR"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 591,  0,  6, "GLB"        , "Globe"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 592,  0,  6, "GAME"       , "GameCredits"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 593,  0,  6, "GML"        , "Game League Coin"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 594,  0,  6, "GNS"        , "Gnosis"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 595,  0,  6, "GOLD"       , "Crypto-Gold"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 596,  0,  6, "GPC"        , "GROUPCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 597,  0,  6, "GPUC"       , "GPUCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 598,  0,  6, "GRCX"       , "Gridcoin Classic"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 599,  0,  6, "GRS"        , "GroestlCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 600,  0,  6, "GUE"        , "GUE"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 601,  0,  6, "H2O"        , "Hidrominer"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 602,  0,  6, "HIRO"       , "HIRO"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 603,  0,  6, "HOT"        , "HOT"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 604,  0,  6, "HUC"        , "HUC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 605,  0,  6, "HVC"        , "HVC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 606,  0,  6, "HYP"        , "HYP"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 607,  0,  6,  "HZ"        , "HZ"                                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 608,  0,  6, "IFC"        , "IFC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 609,  0,  6, "ITC"        , "ITC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 610,  0,  6, "IXC"        , "IXC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 611,  0,  6, "JLH"        , "JLH"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 612,  0,  6, "JPC"        , "JPC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 613,  0,  6, "JUG"        , "JUG"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 614,  0,  6, "KDC"        , "KDC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 615,  0,  6, "KEY"        , "KEY"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 616,  0,  6, "LC"         , "LC"                                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 617,  0,  6, "LCL"        , "LCL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 618,  0,  6, "LEAF"       , "LEAF"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 619,  0,  6, "LGC"        , "LGC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 620,  0,  6, "LOL"        , "LOL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 621,  0,  6, "LOVE"       , "LOVE"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 622,  0,  6, "LQD"        , "LQD"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 623,  0,  6, "LTBC"       , "LTBC"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   5,  1,  6, "LTC"        , "Litecoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 625,  0,  6, "LTCX"       , "LTCX"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 626,  0,  6, "MAID"       , "MaidSafeCoin"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 627,  0,  6, "MAST"       , "MAST"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 628,  0,  6, "MAX"        , "MAX"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 629,  0,  6, "MCN"        , "MCN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 630,  0,  6, "MEC"        , "MEC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 631,  0,  6, "METH"       , "METH"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 632,  0,  6, "MIL"        , "MIL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 633,  0,  6, "MIN"        , "MIN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 634,  0,  6, "MINT"       , "MINT"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 635,  0,  6, "MMC"        , "MMC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 636,  0,  6, "MMNXT"      , "MMNXT"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 637,  0,  6, "MMXIV"      , "MMXIV"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 638,  0,  6, "MNTA"       , "MNTA"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 639,  0,  6, "MON"        , "MON"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 640,  0,  6, "MRC"        , "MRC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 641,  0,  6, "MRS"        , "MRS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 642,  0,  6, "OMNI"       , "OMNI"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 643,  0,  6, "MTS"        , "MTS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 644,  0,  6, "MUN"        , "MUN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 645,  0,  6, "MYR"        , "MYR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 646,  0,  6, "MZC"        , "MZC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 647,  0,  6, "N5X"        , "N5X"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 648,  0,  6, "NAS"        , "NAS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 649,  0,  6, "NAUT"       , "NAUT"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 650,  0,  6, "NAV"        , "NAV"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 651,  0,  6, "NBT"        , "NBT"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 652,  0,  6, "NEOS"       , "NEOS"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 653,  0,  6, "NL"         , "NL"                                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 654,  0,  6, "NMC"        , "NMC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 655,  0,  6, "NOBL"       , "NOBL"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 656,  0,  6, "NOTE"       , "NOTE"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 657,  0,  6, "NOXT"       , "NOXT"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 658,  0,  6, "NRS"        , "NRS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 659,  0,  6, "NSR"        , "NSR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 660,  0,  6, "NTX"        , "NTX"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 661,  0,  6, "NXT"        , "NXT Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 662,  0,  6, "NXTI"       , "NXTI"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 663,  0,  6, "OPAL"       , "OPAL"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 664,  0,  6, "PAND"       , "PAND"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 665,  0,  6, "PAWN"       , "PAWN"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 666,  0,  6, "PIGGY"      , "PIGGY"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 667,  0,  6, "PINK"       , "PINK"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 668,  0,  6, "PLX"        , "PLX"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 669,  0,  6, "PMC"        , "PMC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 670,  0,  6, "POT"        , "POT"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 671,  0,  6, "PPC"        , "PPC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 672,  0,  6, "PRC"        , "PRC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 673,  0,  6, "PRT"        , "PRT"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 674,  0,  6, "PTS"        , "PTS"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 675,  0,  6, "Q2C"        , "Q2C"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 676,  0,  6, "QBK"        , "QBK"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 677,  0,  6, "QCN"        , "QCN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 678,  0,  6, "QORA"       , "QORA"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 679,  0,  6, "QTL"        , "QTL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 680,  0,  6, "RBY"        , "RBY"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 681,  0,  6, "RDD"        , "ReddCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 682,  0,  6, "RIC"        , "RIC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 683,  0,  6, "RZR"        , "RZR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 684,  0,  6, "SDC"        , "SDC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 685,  0,  6, "SHIBE"      , "SHIBE"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 686,  0,  6, "SHOPX"      , "SHOPX"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 687,  0,  6, "SILK"       , "SILK"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 688,  0,  6, "SJCX"       , "SJCX"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 689,  0,  6, "SLR"        , "SLR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 690,  0,  6, "SMC"        , "SMC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 691,  0,  6, "SOC"        , "SOC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 692,  0,  6, "SPA"        , "SPA"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 693,  0,  6, "SQL"        , "SQL"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 694,  0,  6, "SRCC"       , "SRCC"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 695,  0,  6, "SRG"        , "SRG"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 696,  0,  6, "SSD"        , "SSD"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 697,  0,  6, "STR"        , "STR"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 698,  0,  6, "SUM"        , "SUM"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 699,  0,  6, "SUN"        , "SUN"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 700,  0,  6, "SWARM"      , "SWARM"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 701,  0,  6, "SXC"        , "SXC"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 702,  0,  6, "YNC"        , "SYNC"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 703,  0,  6, "SYS"        , "SysCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 704,  0,  6, "TAC"        , "TalkCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 705,  0,  6, "TOR"        , "TORCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 706,  0,  6, "TRUST"      , "Crypto Trust Network"                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 707,  0,  6, "TWE"        , "TWE"                                  );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 708,  0,  6, "UIS"        , "Unitus"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 709,  0,  6, "ULTC"       , "Umbrella-LTC"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 710,  0,  6, "UNITY"      , "SuperNET"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 711,  0,  6, "URO"        , "UroCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 712,  0,  6, "USDE"       , "USDe Coin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   8,  1,  6, "USDT"       , "Tether"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 714,  0,  6, "UTC"        , "UltraCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 715,  0,  6, "UTIL"       , "UTIL"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 716,  0,  6, "UVC"        , "UniversityCoin"                       );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 717,  0,  6, "VIA"        , "Viacoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 718,  0,  6, "VOOT"       , "Crypto VOOT"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 719,  0,  6, "VRC"        , "VeriCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 720,  0,  6, "VTC"        , "Vertcoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 721,  0,  6, "WC"         , "WinCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 722,  0,  6, "WDC"        , "WorldCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 723,  0,  6, "WIKI"       , "WIKI"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 724,  0,  6, "WOLF"       , "CryptoWolf"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 725,  0,  6, "X13"        , "X13 Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 726,  0,  6, "XAI"        , "Sapience AIFX"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 727,  0,  6, "XAP"        , "Apollon"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 728,  0,  6, "XBC"        , "Bitcoin Plus"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 729,  0,  6, "XC"         , "XCurrency"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 730,  0,  6, "XCH"        , "ClearingHouse"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 731,  0,  6, "XCN"        , "Crypton,ite"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 732,  0,  6, "XCP"        , "CounterParty"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 733,  0,  6, "XCR"        , "Crypti"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 734,  0,  6, "XDN"        , "DigitalNote"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 735,  0,  6, "XDP"        , "DogeParty"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 736,  0,  6, "XHC"        , "HonorCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 737,  0,  6, "XLB"        , "LibertyCoin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 738,  0,  6, "XMG"        , "Magi"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 739,  0,  6, "XMR"        , "Monero"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 740,  0,  6, "XPB"        , "PebbleCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 741,  0,  6, "XPM"        , "PrimeCoin"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   3,  0,  6, "XRP"        , "Ripple"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 743,  0,  6, "XSI"        , "StabilityShares"                      );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 744,  0,  6, "XST"        , "Stealth"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 745,  0,  6, "XSV"        , "SilliconValleyCoin"                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 746,  0,  6, "XUSD"       , "CoinoUSD"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 747,  0,  6, "XXC"        , "Creds XXC"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 748,  0,  6, "YACC"       , "YACCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 749,  0,  6, "YANG"       , "YangCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 750,  0,  6, "YC"         , "YellowCoin"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 751,  0,  6, "YIN"        , "YinCoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 752,  0,  6, "XVC"        , "VCash"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 753,  0,  6, "FLO"        , "Florin"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 754,  0,  6, "XEM"        , "NEM/XEM"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 755,  0,  6, "ARCH"       , "ARCHCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 756,  0,  6, "HUGE"       , "CryptoHuge"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 757,  0,  6, "GRC"        , "GridCoin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 758,  0,  6, "IOC"        , "I/O Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 759,  0,  6, "INDEX"      , "INDEX"                                );

INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 761,  0,  6, "SC"         , "Siacoin"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 762,  0,  6, "BCY"        , "BitCrystals"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 763,  0,  6, "EXP"        , "Expanse"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 764,  0,  6, "FCT"        , "Factom"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 765,  0,  6, "BITUSD"     , "bitUSD"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 766,  0,  6, "BITCNY"     , "bitCNY"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 767,  0,  6, "RADS"       , "Radium"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 768,  0,  6, "AMP"        , "HyperSpace"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 769,  0,  6, "VOX"        , "Voxels"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 770,  0,  6, "DCR"        , "Decred"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 771,  0,  6, "LSK"        , "Lisk"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 772,  0,  6, "DAO"        , "Decentralized Autonomous Organization");
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 773,  0,  6, "LBC"        , "LBRY Credits"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 774,  0,  6, "STEEM"      , "Steem"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 775,  0,  6, "SBD"        , "Steem Dollars"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 776,  0,  6, "ETC"        , "Ethereum Classic"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 777,  0,  6, "REP"        , "Augur"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 778,  0,  6, "ARDR"       , "ARDR"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 779,  0,  6, "ZEC"        , "ZCash"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 780,  0,  6, "STRAT"      , "Stratis"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 781,  0,  6, "NXC"        , "Nexium"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 782,  0,  6, "PASC"       , "Pascal Coin"                          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 783,  0,  6, "GNT"        , "Golem"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 784,  0,  6, "GNO"        , "Gnosis"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   4,  0,  6, "BCH"        , "Bitcoin Cash"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 786,  0,  6, "ZRX"        , "0x"                                   );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 787,  0,  6, "CVC"        , "Civic"                                );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 788,  0,  6, "OMG"        , "OmiseGO"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 789,  0,  6, "GAS"        , "GAS Neo"                              );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 790,  0,  6, "STORJ"      , "Decentralized Cloud Storage"          );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   6,  0,  6, "EOS"        , "Crypt/EOS"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 792,  1,  6, "USDC"       , "USD Coin"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 793,  0,  6, "SNT"        , "Status"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 794,  0,  6, "KNC"        , "Kyber Network"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 795,  0,  6, "BAT"        , "Basic Attentio Token"                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 796,  0,  6, "LOOM"       , "LOOM Networks"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 797,  0,  6, "QTUM"       , "Qtum"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 798,  0,  6, "BNT"        , "Bancor"                               );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 799,  0,  6, "MANA"       , "Decentraland"                         );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 800,  0,  6, "FOAM"       , "FOAM Protocol"                        );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 801,  0,  6, "BCHABC"     , "Bitcoin Cash ABC"                     );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 802,  0,  6, "BCHSV"      , "Bitcoin SV"                           );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 803,  0,  6, "NMR"        , "Numerate"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 804,  0,  6, "POLY"       , "PolyMath"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 805,  0,  6, "LPT"        , "Livepeer"                             );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 999,  1,  2, "USD"        , "US Dollar"                            );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 998,  1,  2, "EUR"        , "Euro"                                 );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 100,  1,  2, "ALPHA"      , "Alpha Finance Lab"                    );
INSERT INTO CURRENCIES (PRTY, ACTIVE, DECIMALS, SYMBOL, NAME) VALUES (   3,  1,  2, "BNB"        , "Binance Coin"                         );
commit;