
-- Proveedores de datos
DELETE FROM PROVIDERS;       
INSERT INTO PROVIDERS  (PROVIDER, NAME, PRTY, ICON, OBJECT)   VALUES ('POL',   'Poloniex'   , 1  ,"poloniex.png"  ,"Poloniex");

-- Intercambios
DELETE FROM EXCHANGES;
INSERT INTO EXCHANGES  (CAMERA, SYMBOL, ACTIVE)  VALUES ("YATA",  "BTC",  1);
INSERT INTO EXCHANGES  (CAMERA, SYMBOL, ACTIVE)  VALUES ("YATA",  "ETH",  1);
INSERT INTO EXCHANGES  (CAMERA, SYMBOL, ACTIVE)  VALUES ("YATA",  "USDT", 1);
INSERT INTO EXCHANGES  (CAMERA, SYMBOL, ACTIVE)  VALUES ("YATA",  "XRP",  1);
INSERT INTO EXCHANGES  (CAMERA, SYMBOL, ACTIVE)  VALUES ("YATA",  "LTC",  1);
INSERT INTO EXCHANGES  (CAMERA, SYMBOL, ACTIVE)  VALUES ("YATA",  "BCH",  1);

COMMIT;