
DROP DATABASE IF EXISTS YATABase;
CREATE DATABASE YATABase CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP DATABASE IF EXISTS YATA;
CREATE DATABASE YATA CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP DATABASE IF EXISTS YATATest;
CREATE DATABASE YATATest CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP DATABASE IF EXISTS YATASimm;
CREATE DATABASE YATASimm CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP DATABASE IF EXISTS YATATpl;
CREATE DATABASE YATATpl CHARACTER SET utf8 COLLATE utf8_general_ci;
