modPosInput = function(id, title) {
    ns = NS(id)
    left = tagList(
         fluidRow(column(4, "Updated:"),column(8, yuiLabelDate(ns("dtLast"))))
        ,fluidRow(column(4, "Interval"),column(8, yuiNumericInput(ns("numInterval"))))
        ,fluidRow(column(4, "History") ,column(8, yuiNumericInput(ns("numDays"), value=15,step=1,min=7,max=60)))
        ,hr() 
        ,yuiTitle(5, "Show")
        ,fluidRow(column(4, yuiTitle(6, "Monitors"))
                 ,column(8, style="text-align: right;", yuiCheck(ns("chkMonitors")))
          )
        ,fluidRow(column(4, yuiTitle(6, "Operations"))
                 ,column(8, style="text-align: right;", yuiCheck(ns("chkOper")))
          )
        ,hr()
        ,yuiTitle(5, "Plots")
        ,fluidRow(column(4, "Left"),  column(8, yuiCombo(ns("cboPlot1"))))
        ,fluidRow(column(4, "Right"), column(8, yuiCombo(ns("cboPlot2"))))
        ,hr() 
        ,yuiTitle(5, "Data")
        # ,fluidRow( column(4, yuiTitle4("Data"))
        #           ,column(8, style="text-align: right;", awesomeCheckbox(inputId = "Id045",NULL,value = TRUE)))      
        ,fluidRow(column(4, "Left"),  column(8, yuiCombo(ns("cboData1"))))
        ,fluidRow(column(4, "Right"), column(8, yuiCombo(ns("cboData2"))))
      
        ,hr() 
        ,yuiTitle(5, "Best")
        ,fluidRow(column(4, "Top"),    column(8, yuiIntegerInput(ns("numBestTop"),value=15,step=1,min=5,max=30)))
        ,fluidRow(column(4, "Period"), column(8, yuiCombo(ns("cboBestFrom"), 
                                                   choices=c("Hora"=1,"Dia"=2,"Semana"=3,"Mes"=4),selected=2)))
        ,tags$br()
        ,yuiFlex(yuiBtnOK(ns("btnLayoutOK"),"Aceptar"), yuiBtnKO(ns("btnLayoutKO"),"Anular"))
    )
    main = tagList(
       fluidRow(id=ns("block_1"), fluidRow(tags$div(id=ns("monitor"), class="yata_monitors")))
      ,fluidRow(id=ns("block_2")
         ,column(6, fluidRow(id=ns("block_2_1"),yuiPlot(ns("plot1"))))
         ,column(6, fluidRow(id=ns("block_2_2"),yuiPlot(ns("plot2"))))
      )
      ,fluidRow(id=ns("block_3")
         ,column(6, fluidRow(id=ns("block_3_1")))
         ,column(6, fluidRow(id=ns("block_3_2")))
      )
      #,hidden(tags$div(id=ns("blocks")#
      ,yuiBlocks(ns("blocks")
          ,yuiBox(ns("Best"), yuiLabelText(ns("lblBest")), yuiDataTable(ns("tblBest")))
          ,yuiBox(ns("Top"),  yuiLabelText(ns("lblTop")),  yuiDataTable(ns("tblTop")))
          ,yuiBox(ns("Fav"),  yuiLabelText(ns("lblFav")),  yuiDataTable(ns("tblFav")))
          ,tags$div(id=ns("Position"), style="width: 100%;"
                    ,yuiBox(ns("PosGlobal"), "Posicion Global", yuiDataTable(ns("tblPosGlobal")))
           )
       )
      #)
    )
    list(left=left, main=main, right=NULL)
}
