---
title: "YATA Configuracion"
author: "Grandez"
date: "6/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Virtualizacion

Tenemos dos maneras de virtualizar:

- Maquina virtual
- Docker

El problema es que se "pegan" entre ellas

### Virtual Box

Para que funcione VirtualBox deben estar desactivadas las funciones del Hypervisor de Windows:

1- Activar o desactivar caracterisiticas de Windows
2. Desactivar Hyper-V
3. Plataforma de maquina virtual
4. Plataforma de hypervisor

En Ubuntu las carpetas compartidas se montan en /media
Pero es recomendable crear otras carpetas, en esta instalacion 

1- Creamos la carpeta host en el directorio raiz
2- Le damos permisos publicos
3. Por cada carpeta compartida:
   3.1 Creamos un sibdirectorio con un nombre amigable: p.e. yata
   3.2 Montamos el sistema de archivos
       `mount -t vboxsf sharedFolderName /host/yata
       
Si hay problemas con los montajes

cd /opt/VBoxGuestAdditions-*/init 
sudo ./vboxadd setup

### Docker

TO DO JGG

