# Criptomonedas

Una criptomoneda es un "ecosistema" autocontenido; ¿Qué queremos decir con esto? Que no existe fuera del sistema en el que se ha generado y no conoce nada del exterior.

Veamos un ejemplo genérico:

Estamos diseñando un sistema o un negocio que va a existir dentro de una criptomoneda (_Our Super Currency_ -OSC-); es decir, ni la financiación ni las operaciones van a utilizar monedas fiduciarias; ¿Por donde empezamos? ... ¡Por el inicio! Creamos el número de monedas que queremos poner en circulación, bien como monedas en total, bien como monedas iniciales; pongamos por ejemplo un millón de monedas, esta operación, que es la primera de todo el sistema se suele denominar _genesis_

En este punto, tenemos una operación que no tiene "padre" (no viene de ningún sitio) y un monedero/wallet con una saldo de 1.000.000. ¿Cual es el valor de esto? En principio ninguno, solo ha sido un artificio técnico, es un número en una aplicación.

Como el sistema lo estamos diseñando en un equipo de cinco personas, distribuimos la mitad de las monedas entre los integrantes, ahora tenemos un monedero con un saldo de 500.000 monedas y cinco monederos mas (crear un monedero no tiene ningún coste) con un saldo de 100.000 cada uno; ademas cada monedero solo puede ser manejado por su propietario a través de cierto tipo de claves.

En este momento, podríamos entender este proceso como una repartición equitativa de la propiedad del sistema, hemos definido un millón de partes y cada socio tiene el 10%, quedando el 50% para futuros usos. Dado que cada uno de ee ellos es propietario de su saldo, pongamos por ejemplo que uno de ellos, le da la mitad de su saldo a su hijo. El proceso es sencillo:

- Creamos un nuevo monedero (ya hemos indicado que se pueden crear tantos como se quiera) propiedad de su hijo
- El padre ejecuta un traspaso de 50.000 monedas a ese monedero (lo que en el mundo financiero llamaríamos una transferencia)

Ahora tenemos 7 cuentas, cuatro con un saldo de 100.000, dos con un saldo de 50.000 y, digamos la cuenta 0, con un saldo de 500.000

¿Que valor tienen esas cuentas? Ahora ya la respuesta varia, de manera general diríamos que ninguno, pero si lo que se está haciendo es tomar alguna decisión acerca del proyecto, entonces si tiene un valor, por que la opinión de cada poseedor de las monedas tiene un peso especifico en función del saldo de su monedero.

Detectamos que necesitamos otra persona para el proyecto, la incorporamos y le asignamos como a los demás, 100.000 monedas de la cuenta 0, la cual ya solo dispone de 400.000, y por otro lado, estimamos que el coste del proyecto es de 200.000 horas y establecemos un criterio de valoración propio que asocia cada hora de trabajo dedicada al proyecto un valor de una moneda, de manera que ahora tengo un saldo, no de 400.000 monedas si no de 200.000 horas de trabajo globales, 200.000 monedas y ademas, cuando uno de los miembros dedique su tiempo a ayudar a otro también se incurre en una transacción trabajo/moneda.

**Ya tenemos un sistema de comercio y de valoración.**

Ahora las monedas si tienen un valor intrínseco y definido para los poseedores de ellas. En este momento, por ejemplo yo que soy vago, puedo decidir hacer mi trabajo que me llevará 100 horas o bien pagarle 100 monedas a otro para que las haga por mi (Considerando tambien que perderé un 1% de mi capacidad de decisión). Y según quien dedique mas esfuerzo al proyecto, también ganará mas peso en la toma de decisiones, lo cual parece, a primera vista, justo y lógico (Esto es lo que se denomina PoS o Prueba de Stakeholders)

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Ahora aparece una nueva persona ajena al sistema que se ha enterado del mismo, lo considera interesante y quiere incorporarse, ¿Como lo hace?:

Podríamos decir, fácil, se crea una cuenta en el sistema. Pero no puede trabajar en el proyecto -ni le interesa- asi que lo unico que consigue es tener una cuenta con un saldo 0



