## Cartera

Técnicamente Una cartera o __portfolio__ es el conjunto de los activos que se poseen, normalmente estructurados en libros de acuerdo con su alcance (corto plazo, largo, autocartera, etc.)


En e|ste manual |tilizaremos e|te término|para ident|ficar un conjunto de activos en una o varias cámaras que comparten unas características y una estrategia de inversión común.

Veamos con mas detalle que entendemos por estrategia y características:

Si tomamos como referencia las bolsas y los mercados de inversión fiduciarios, sabemos (o deberíamos saber) que cuando acudes a una entidad financiera o de inversión para invertir en esos mercados los primero que debes rellenar es un formulario para evaluar el perfil de riesgo y permitir el acceso o no a determinados productos. En este formulario, aparte de otros datos de interés, se plantean preguntas para averiguar el nivel de conocimiento financiero del usuario y en consecuencia su conocimiento acerca del producto deseado.

Dicho de otra forma, si no tenemos unos conocimientos "avanzados" va a ser dificil -que no imposible- que nadie nos permita "__hacer un forward con titulizacion de un contrato de swap a medio plazo indexado al DJ sobre una divisa no cotizada con una cobertura por default ...__"

Actualmente este formulario califica al cliente como:

- Conservador
- Moderado
- Agresivo

Basándonos en esta idea y la de los libros mencionada anteriormente podemos establecer una cierta clasificación o enfoque de cartera:


|           | Conservador | Moderado | Agresivo |
|-----------|-------------|----------|----------|
| Intradia  |             |          |          |
| Corto     |             |          |          |
| Medio     |             |          |          |
| Largo     |             |          |          |
| Inversion |             |          |          |

Unicamente con esta tabla, basada en en el perfil de riesgo y el ámbito de las operaciones tener 15 tipos de carteras.

Y, aunque la operativa sea la misma técnicamente, la estrategia, la operativa y el análisis para la toma de decisiones es diferente para cada una de las posibilidades por lo que necesitamos la información adecuada en función de las características de la cartera.

Dicho de otro modo, si estoy trabajando en una cartera intradía (abro y cierro posiciones a lo largo del mismo dia) necesito saber la cotización de cada activo __casi__ en tiempo real, pero esa misma información no me sirve de nada si estoy con una cartera a largo plazo (inversiones a 12 o mas meses) o de inversión (cuasi permanentes), de hecho, para estas carteras no me es relevante tan siquiera las variaciones diarias o semanales, de la misma forma que tampoco me interesa en la cartera intradia como se comporta el activo respecto a la semana o el mes pasado.

Desde el punto de vista de lo que hemos llamado "perfil de riesgo" la situación es análoga pero aplicada al conjunto de los activos sobre los que se puede operar. Si en un determinado mercado operan por ejemplo 2.000 activos, sólo un pequeño porcentaje de ellos son denominados "de referencia", por ejemplo, el IBEX 35 referencia 35 activos en España y el NASDAQ 100 de Nueva York, normalmente estos activos suelen ser "mas estables" y __se supone__ que actúan como referencia para el resto del mercado; estos indicadores parecen los apropiados para un perfil conservador, con lo que se ahorra el trabajo de filtrar o ignorar la información relativa a todos los otros activos.

Por otro lado, una persona con un perfil agresivo es mucho mas posible que se centre en otro tipo de activos y/u oportunidades, pudiendo incluso ignorar directamente el comportamiento de estos "__big blue__" por lo que necesita la información de todos los activos disponibles.

Una vez explicados estos conceptos resulta evidente la siguiente recomendación:

**Una cartera para cada tipo de estrategia operativa y de inversión**


### Atributos de una cartera

Dado que en el sistema es posible crear tantas carteras como se desee (mas carteras, mas compleja la administración de las mismas -__no free lunch today__-)

Veamos que atributos podemos definir para cada una de ellas:



#### Scope

Nos indica cual es el plazo medio de las operaciones:

|           | Periodo      |
|-----------|--------------|
| Intradia  | 0-2  Dias    |
| Corto     | 1-2  Semanas |
| Medio     | 1-3  Meses   |
| Largo     | 3-12 Meses   |
| Inversion |              |

Notese que no estamos obligados a abrir y cerrar posiciones dentro de esos intervalos de tiempo, unicamente nos indica el plazo tipico al que planteamos las operaciones en esa cartera.

Este atributo tiene su importancia por que es el que define __a priori__ el tipo de información que se va a mostrar y el comportamiento de algunos modelos análiticos.

Por ejemplo, para una cartera de intradia la información seleccionada por defecto afectará a la sesión actual y de uno o dos dias antes, mientras que para una una cartera de medio plazo la informacion hara referencia a los datos historicos diarios y para una a largo a los semanales.

Para los modelos, este atributo tambien determina los datos a procesar. Por ejemplo, para el modelo de variación cúbica, se toman cinco datos de referencia (SEE modelo de variacion), en función de este atributo pueden ser (valores por defecto):

1-2-3-7-14 Dias
1-3-14-21-30 Dias
1-3-6-9-12 Meses

#### Target

Este atributo hace referencia al tipo de activo con el que vamos a trabajar:

- Monedas/criptomonedas
- Tokens 

Un perfil mas conservador evitará los __tokens__ mientra que uno mas agresivo puede estar interesado en ellos

#### Selective

Este atributo hace referencia al volumen de activos que deseamos considerar. Los activos están clasificados según un orden ascendente de importancia en los mercados (1 es el mas importante), lo cual tambien nos indica la fiabilidad y/o estabilidad de ese activo.

Si se establece este atributo unicamente se considerarán las monedas y/o tokens que esten dentro de ese rango

En el momento de escribir esto el sistema maneja unas 2500 monedas y unos 7000 tokens y es un número que previsiblemente irá aumentando con el tiempo por lo que es mas que conveniente, salvo en carteras especiales, manejar un subconjunto de estas monedas, ya no únicamente por un problema de sobreinformación si no también para una operativa mas ágil.

La clasificación de las monedas no es un dato estático si no que se va actualizando periodicamente. No obstante, si una moneda "sale" del selectivo pero tenemos posición (por ejemplo pasa del puesto 50 al 55) en ella se seguirá mostrando como si perteneciera al selectivo indicado.



